name: "Build and Push Docker Image to the container image registry (multi-arch: amd64 & arm64)"

on:
  workflow_call:

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - name: Log in to GitHub Container Registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag name (release only)
        id: extract_tag
        if: ${{ github.event_name == 'release' }}
        run: echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Extract flavor
        id: flavor
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "FLAVOR=" >> $GITHUB_OUTPUT
          else
            echo "FLAVOR=-dev" >> $GITHUB_OUTPUT
          fi

      - name: Normalize repository name (lowercase)
        id: repo_name
        run: |
          echo "REPO_LOWERCASE=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT

      - name: Generate Docker image metadata
        id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5
        with:
          images: ghcr.io/${{ steps.repo_name.outputs.REPO_LOWERCASE }}
          flavor: |
            latest=auto
            suffix=${{ steps.flavor.outputs.FLAVOR }}
          tags: |
            ${{ steps.extract_tag.outputs.TAG_NAME }}
            latest

      - name: Build and push Docker image (amd64 & arm64)
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,mode=max
          cache-to: type=gha,mode=max
          build-args: |
            COMMIT_SHA=${{ github.sha }}
